### ISSUE TITLE
Warnings not showing up

### ISSUE THREAD

**Issue by steentje34** [vanderbilt-redcap/big-data-import#2] opened 2019-07-17 14:50 UTC
Even though a data import should have warnings, the module shows "... completed successfully for ...", never "... completed with warnings for ...". This probably has something to do with the function quoted below, but I haven't got to the bottom of this. Could you have a look?

https://github.com/vanderbilt-redcap/big-data-import/blob/8d57f8abb3189eca7c26eb0937550dc33e2c82b0/BigDataImportExternalModule.php#L395-L407

**Comment by knil-maloon** [comment] 2019-07-17 18:47
Hi @steentje34 the only problem with displaying the warnings is that, as the files can be extremely huge, saving and displaying the data can take a lot of memory. That's also one of the reasons why we aren't showing all the returning values after saving the information.

**Comment by steentje34** [comment] 2019-07-18 07:33
Hi @knil-maloon, while I fully understand that displaying all warnings can be extremely huge, the [code](https://github.com/vanderbilt-redcap/big-data-import/blob/8d57f8abb3189eca7c26eb0937550dc33e2c82b0/BigDataImportExternalModule.php#L321-L325) suggests that the message in the log should be different depending on the presence of warnings in the imported batch:

1. No warnings: Import #1 completed succesfully for batch 1 of 809
2. Warnings: Import #1 completed with warnings for batch 1 of 809

However, for a test import that results in known warnings, the first message (... completed successfully ...) is shown.

**Comment by knil-maloon** [comment] 2019-07-18 11:59
Hi @steentje34  I have asked if we can develop this as I have to check if we have time to work on it because it would be an addition and not a bug. I also can see people wanting to see those warnings if we add the text.

**Comment by steentje34** [comment] 2019-07-18 13:26
Hi @knil-maloon, I know that this is not a major issue, but how is this considered to be an addition and not a bug?
The code is already written, but it just does not behave as expected.
https://github.com/vanderbilt-redcap/big-data-import/blob/8d57f8abb3189eca7c26eb0937550dc33e2c82b0/BigDataImportExternalModule.php#L321-L325

**Comment by knil-maloon** [comment] 2019-07-18 15:14
Hi @steentje34  I meant in the sense that it's not an immediate bug, sorry about the confusion. As soon as I have time I will work on it.

**Comment by knil-maloon** [comment] 2019-07-19 17:00
Closing this as it will be available in the next update once it's finished.

**Closed** 2019-07-19 16:59 UTC
